---
openapi: 3.0.0
info:
  description: This is a simple Company API
  version: "1.0.0"
  title: Company
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
- url: https://virtserver.swaggerhub.com/kunalSalunkhe/Company/1.0.0
- url: https://localhost:8080
- url: https://entlogics.free.beeceptor.com/ipl
paths:
  /companies:
    get:
      description: 
        get list of all awards of IPL
      operationId: getAllCompanies
      responses:
        "200":
          description: list of all companiess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/companies'
              
    post:
      operationId: addNewCompany 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addCompany'
              
      responses:
        "201":
          description: new Company created
        "400":
          description: bad input parameter
          
          
  /companies/{company_id}:
    get:
      parameters:
        - name: company_id
          in: path
          required: true
          schema:
            type: integer
      operationId: getCompany
      responses:
        '200':
          description: Company details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
                
                
    put:
      operationId: updateCompany
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/company'
              
      responses:
        "200":
          description: Season is updated
    
    delete:
      operationId: deleteCompany
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Company is deleted
    
      
            

components:
  schemas:
    companies:
      type: array
      items:
        properties:
          company_id:
            type: integer
            format: int64
          company_name:
            type: string
          ceo:
            type: string
          established_in:
            type: string
          email_id:
            type: string
          headquarter:
            type: string
          country:
            type: string
          website:
            type: string
          description:
            type: string
          
      example:
        - company_id : 1
          company_name: "Marvel Studio"
          ceo: "Kevin Feige"
          established_in: 21-04-1993
          email_id: "marvelstudio@co.in"
          headquarter: "New York"
          country: "United States"
          website: "www.marvel.com"
          description: "Marvel Studios is known for the production of the Marvel Cinematic Universe films, based on characters that appear in Marvel Comics publications"
        - company_id : 2
          company_name: "Sony Pictures"
          ceo: "Tony vinciquerra"
          established_in: 12-05-1987
          email_id: "sonypictures@co.in"
          headquarter: "California"
          country: "United States"
          website: "www.sonypictures.com"
          description: "Sony Pictures is an American diversified multinational mass media and entertainment conglomerate that produces, acquires, and distributes filmed entertainment through multiple platforms"
              
            
    company:
      type: object
      properties:
          company_id:
            type: integer
            format: int64
          company_name:
            type: string
          ceo:
            type: string
          established_in:
            type: string
          email_id:
            type: string
          headquarter:
            type: string
          country:
            type: string
          website:
            type: string
          description:
            type: string
      example:
          company_id : 1
          company_name: "Marvel Studio"
          ceo: "Kevin Feige"
          established_in: 21-04-1993
          email_id: "marvelstudio@co.in"
          headquarter: "New York"
          country: "United States"
          website: "www.marvel.com"
          description: "Marvel Studios is known for the production of the Marvel Cinematic Universe films, based on characters that appear in Marvel Comics publications"  
        
        
    addCompany:
      type: object
      properties:
          company_name:
            type: string
          ceo:
            type: string
          established_in:
            type: string
          email_id:
            type: string
          headquarter:
            type: string
          country:
            type: string
          website:
            type: string
          description:
            type: string
      example:
          company_name: "Marvel Studio"
          ceo: "Kevin Feige"
          established_in: 21-04-1993
          email_id: "marvelstudio@co.in"
          headquarter: "New York"
          country: "United States"
          website: "www.marvel.com"
          description: "Marvel Studios is known for the production of the Marvel Cinematic Universe films, based on characters that appear in Marvel Comics publications"    
          
        
    
          
          
        
        
            
      
          
                  
  
          
    
              
              
            
            
          
            